# Genders
Gender.create(
                {
                  name: "Female",
                  abbreviation: "F"
                },
                {
                  name: "Male",
                  abbreviation: "M"
                }
              )

# Languages
Language.create(
                  { name: "Akan" },
                  { name: "Akposso" },
                  { name: "Algonquian-Wakashian" },
                  { name: "American" },
                  { name: "Ancient Celtic" },
                  { name: "Ancient German" },
                  { name: "Arabic" },
                  { name: "Aramaic" },
                  { name: "Burmese" },
                  { name: "Celtic" },
                  { name: "Chinese"},
                  { name: "Choctaw" },
                  { name: "Czech"},
                  { name: "Dutch" },
                  { name: "English" },
                  { name: "Farsi" },
                  { name: "French" },
                  { name: "Gaelic" },
                  { name: "German" },
                  { name: "Greek" },
                  { name: "Hawaiian" },
                  { name: "Hebrew" },
                  { name: "Hindi" },
                  { name: "Igbo" },
                  { name: "Indian" },
                  { name: "Irish Gaelic" },
                  { name: "Iroquoian" },
                  { name: "Italian" },
                  { name: "Japanese" },
                  { name: "Khmer" },
                  { name: "Latin" },
                  { name: "Middle English" },
                  { name: "Mongolian" },
                  { name: "Norman French" },
                  { name: "Norse" },
                  { name: "Norwegian" },
                  { name: "Old English" },
                  { name: "Old French" },
                  { name: "Old Norse" },
                  { name: "Old Welsh" },
                  { name: "Persian" },
                  { name: "Phoenician" },
                  { name: "Roman" },
                  { name: "Russian" },
                  { name: "Sanskrit" },
                  { name: "Scots Gaelic" },
                  { name: "Siouan" },
                  { name: "Slavic" },
                  { name: "Spanish" },
                  { name: "Swahili" },
                  { name: "Vietnamese" },
                  { name: "Welsh" },
                  { name: "West African" },
                  { name: "Xhosa" },
                  { name: "Yiddish" },
                  { name: "Yoruba" }
                )
